name: Build pandas
description: Rebuilds the C extensions and installs pandas
runs:
  using: composite
  steps:
    - name: Environment Detail
      run: |
        if which mamba; then
          mamba info
          mamba list
          mamba info | grep -Ei 'environment.+:' | grep -qEiv 'environment.+:.+none'
        fi
        if which pip; then
          pip list
        fi
        python --version
      shell: bash -el {0}

    - name: Build Pandas
      run: |
        which python
        which pip
        time python setup.py build_ext -v -j 2
        pip install -v -e . --no-build-isolation --no-use-pep517 --no-index
      shell: bash -el {0}

    - name: Build Version
      run: pushd /tmp && python -c "import pandas; pandas.show_versions();" && popd
      shell: bash -el {0}
