name: Build pandas
description: Rebuilds the C extensions and installs pandas
runs:
  using: composite
  steps:
    - name: Environment Detail
      run: |
        if which mamba 2>/dev/null; then
          mamba info
          mamba list
          mamba info | grep -Ei 'environment.+:' | grep -qEiv 'environment.+:.+none'
        fi
        pip list
        python --version
      shell: bash -el {0}

    - name: Build Pandas
      run: |
        which python
        which pip
        # Cannot use parallel compilation on Windows, see https://github.com/pandas-dev/pandas/issues/30873
        j=${{ runner.os == 'Windows' ? 1 : 3 }}
        time python setup.py build_ext -v -j $j
        pip install -v -e . --no-build-isolation --no-use-pep517 --no-index
      shell: bash -el {0}

    - name: Build Version
      run: pushd /tmp && python -c "import pandas; pandas.show_versions();" && popd
      shell: bash -el {0}
