name: sdist

on:
  push:
    branches:
      - main
      - 1.4.x
  pull_request:
    branches:
      - main
      - 1.4.x
    types: [labeled, opened, synchronize, reopened]
    paths-ignore:
      - "doc/**"

jobs:
  sdist:
    #if: ${{ github.event.label.name == 'Build' || contains(github.event.pull_request.labels.*.name, 'Build') || github.event_name == 'push'}}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: bash -el {0}

    strategy:
      fail-fast: false
      matrix:
        # 'numpy-version' is oldest supported NumPy
        include:
          - python-version: "3.8"
            numpy-version: "1.18.5"
          - python-version: "3.9"
            numpy-version: "1.19.4"
          - python-version: "3.10"
            numpy-version: "1.21.3"

    name: sdist Python ${{ matrix.python-version }} NumPy ${{ matrix.numpy-version }}

    concurrency:
      # https://github.community/t/concurrecy-not-work-for-push/183068/7
      group: ${{ github.event_name == 'push' && github.run_number || github.ref }}-${{ matrix.python-version }}-sdist
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }} and install dependencies
      uses: ./.github/actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build pandas sdist
      run: python setup.py sdist --formats=gztar

    - name: Upload sdist artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.python-version }}-sdist.gz
        path: dist/*.gz

    - name: Create environment.yml with Python ${{ matrix.python-version }}, NumPy ${{ matrix.numpy-version }}
      run: |
        cat >> tmp_environment.yml <<EOF
          name: pandas-sdist
          channels:
            - conda-forge
          dependencies:
            - python=${{ matrix.python-version }}
            - setuptools<60
            - numpy=${{ matrix.numpy-version }}
        EOF

    - name: Install Conda enviroment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pandas-sdist
        environment-file: tmp_environment.yml
        channel-priority: strict
        channels: conda-forge
        mamba-version: "0.22"
        use-mamba: true

    - name: Install pandas from sdist
      run: |
        micromamba info
        # Double check that we have the expected NumPy
        pip list
        pip list | egrep -i "numpy.+${{ matrix.numpy-version }}"
        time python -m pip install -v dist/*.gz

    - name: Build Version
      run: |
        pushd /tmp
        python -c "import pandas; pandas.show_versions()"
        # Double check that we have the expected Python and NumPy
        python -c "import pandas; pandas.show_versions()" | egrep -i "python.+: ${{ matrix.python-version }}"
        python -c "import pandas; pandas.show_versions()" | egrep -i "numpy.+: ${{ matrix.numpy-version }}"
        popd
